# Generated by Django 4.1.1 on 2022-09-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('author_club', models.CharField(max_length=50)),
                ('author_category', models.CharField(max_length=10)),
                ('author_practice_level', models.CharField(max_length=15)),
                ('hour', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('location', models.CharField(choices=[('Domicile', 'Domicile'), ('Extérieur', 'Extérieur'), ('Peu Importe', 'Peu Importe')], max_length=100)),
                ('desired_level', models.CharField(max_length=50)),
                ('published_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('published_date',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Website.announce')),
            ],
            options={
                'ordering': ('published_date',),
            },
        ),
    ]
