# Generated by Django 4.1.1 on 2022-09-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('location', models.CharField(choices=[('Exterieur', 'Exterieur'), ('Domicile', 'Domicile')], max_length=100)),
            ],
        ),
    ]
