# Generated by Django 4.1.1 on 2022-09-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='author_region',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
