# Generated by Django 4.1.1 on 2022-09-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('club', models.CharField(max_length=300)),
                ('region', models.CharField(choices=[('Auvergne-Rhône-Alpes', 'Auvergne-Rhône-Alpes'), ('Bourgogne-Franche-Comté', 'Bourgogne-Franche-Comté'), ('Bretagne', 'Bretagne'), ('Centre-Val de Loire', 'Centre-Val de Loire'), ('Corse', 'Corse'), ('Grand Est', 'Grand Est'), ('Hauts-de-France', 'Hauts-de-France'), ('Ile-de-France', 'Ile-de-France'), ('Normandie', 'Normandie'), ('Nouvelle-Aquitaine', 'Nouvelle-Aquitaine'), ('Occitanie', 'Occitanie'), ('Pays de la Loire', 'Pays de la Loire'), ('Provence-Alpes-Côte d’Azur', 'Provence-Alpes-Côte d’Azur')], max_length=255)),
                ('category', models.CharField(choices=[('U6', 'U6'), ('U7', 'U7'), ('U8', 'U8'), ('U9', 'U9'), ('U10', 'U10'), ('U11', 'U11'), ('U12', 'U12'), ('U13', 'U13'), ('U14', 'U14'), ('U15', 'U15'), ('U16', 'U16'), ('U17', 'U17'), ('U18', 'U18'), ('U19', 'U19'), ('U20', 'U20'), ('Sénior', 'Sénior')], max_length=10)),
                ('practice_level', models.CharField(choices=[('Départemental', 'Départemental'), ('Régional', 'Régional'), ('National', 'National'), ('D5', 'D5'), ('D4', 'D4'), ('D3', 'D3'), ('D2', 'D2'), ('D1', 'D1'), ('R4', 'R4'), ('R3', 'R3'), ('R2', 'R2'), ('R1', 'R1')], max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
